# Generated by Django 5.0.7 on 2024-09-25 01:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_certificate',
            field=models.FileField(null=True, upload_to=api.models.candidate_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='cni',
            field=models.FileField(null=True, upload_to=api.models.candidate_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'm'), (0, 'f')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.candidate_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='require_diploma',
            field=models.FileField(null=True, upload_to=api.models.candidate_directory_path),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
