# Generated by Django 5.0.7 on 2024-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_birth_certificate_user_cni_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
