# Generated by Django 5.0.7 on 2024-10-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_examsession_end_time_examsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.examsession'),
        ),
    ]
