# Generated by Django 5.0.7 on 2024-10-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_exam_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam_session',
            new_name='exam_session_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
