# Generated by Django 5.0.7 on 2024-10-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_exam_session_question_exam_session_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam_session_id',
            new_name='exam_session',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
