# Generated by Django 5.0.7 on 2024-10-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_result_exam_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='exam_session',
        ),
    ]
