# Generated by Django 5.0.7 on 2024-10-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_useranswer_exam_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
