# Generated by Django 5.0.7 on 2024-10-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'verbose_name': 'ExamSession', 'verbose_name_plural': 'ExamSessions'},
        ),
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
    ]
